In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import r2_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
df=pd.read_csv("student-mat.csv",sep=';')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [3]:
df.shape

(395, 33)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    str
 1   sex         395 non-null    str
 2   age         395 non-null    int64
 3   address     395 non-null    str
 4   famsize     395 non-null    str
 5   Pstatus     395 non-null    str
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    str
 9   Fjob        395 non-null    str
 10  reason      395 non-null    str
 11  guardian    395 non-null    str
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    str
 16  famsup      395 non-null    str
 17  paid        395 non-null    str
 18  activities  395 non-null    str
 19  nursery     395 non-null    str
 20  higher      395 non-null    str
 21  internet    395 non-null    str
 22  romantic    395 non-null    str
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), str(17)
memory usage: 102.0 KB

In [5]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [6]:
X = df.drop('G3', axis=1)
y = df['G3']

print(X.shape)
print(y.shape)

(395, 32)
(395,)

In [7]:
# LABEL ENCODNG

le=LabelEncoder()

# WE ARE DOING THIS TO ONLY ENCODE THE CATEGORICAL COLUMNS IN THE X
for col in X.columns:
    if X[col].dtype == 'str':
        X[col] = le.fit_transform(X[col])

In [8]:
X.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2
0,0,0,18,1,0,0,4,4,0,4,...,0,4,3,4,1,1,3,6,5,6
1,0,0,17,1,0,1,1,1,0,2,...,0,5,3,3,1,1,3,4,5,5
2,0,0,15,1,1,1,1,1,0,2,...,0,4,3,2,2,3,3,10,7,8
3,0,0,15,1,0,1,4,2,1,3,...,1,3,2,2,1,1,5,2,15,14
4,0,0,16,1,0,1,3,3,2,2,...,0,4,3,2,1,2,5,4,6,10

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(316, 32)
(79, 32)
(316,)
(79,)

In [10]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [11]:
model = Sequential()

# Input Layer + Hidden Layer 1
model.add(Dense(128, activation='relu', input_shape=(32,)))

# Hidden Layer 2
model.add(Dense(64, activation='relu'))

# Hidden Layer 3
model.add(Dense(32, activation='relu'))

# Output Layer
model.add(Dense(1))

# JUST TO SEE THE SUMMARY HOW THE MODEL IS MADE BEFORE TRAINING   ... ONLY FOR MY UNDERSTANDING 
model.summary()

c:\Users\ASUS\Desktop\DEEP LERNING\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         4,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,593 (57.00 KB)

 Trainable params: 14,593 (57.00 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.compile(optimizer='adam',loss='mse')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [13]:
# THIS IS THE MODEL TRAINING 

history = model.fit(X_train,y_train,epochs=50,batch_size=32,validation_split=0.2)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 132.4536 - val_loss: 123.1667
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 120.0128 - val_loss: 112.1031
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 108.0800 - val_loss: 97.8643
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 91.1880 - val_loss: 77.6163
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68.0416 - val_loss: 50.8803
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 41.3605 - val_loss: 25.0135
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 20.5223 - val_loss: 15.7099
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 15.4884 - val_loss: 14.2420
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.2225 - val_loss: 10.9458
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.5291 - val_loss: 10.0004
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1743 - val_loss: 9.3335
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2176 - val_loss: 9.0930
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6635 - val_loss: 8.6990
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.1672 - val_loss: 8.3405
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.7648 - val_loss: 8.1145
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.4486 - val_loss: 7.9093
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.1528 - val_loss: 7.7940
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.8713 - val_loss: 7.6997
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.6407 - val_loss: 7.6629
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.4047 - val_loss: 7.4865
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.1764 - val_loss: 7.2720
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.9617 - val_loss: 7.1068
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.7452 - val_loss: 6.9842
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.5607 - val_loss: 6.8466
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.3661 - val_loss: 6.7698
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.1741 - val_loss: 6.6547
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.9934 - val_loss: 6.5543
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.8074 - val_loss: 6.3944
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.6613 - val_loss: 6.2566
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.5076 - val_loss: 6.0993
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.3528 - val_loss: 6.0742
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.2434 - val_loss: 6.0099
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1392 - val_loss: 5.9597
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0269 - val_loss: 5.7405
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9387 - val_loss: 5.7445
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8572 - val_loss: 5.6856
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7898 - val_loss: 5.5871
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7187 - val_loss: 5.5645
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6601 - val_loss: 5.4712
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6034 - val_loss: 5.4515
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5484 - val_loss: 5.3767
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5089 - val_loss: 5.3638
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4718 - val_loss: 5.3613
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.4350 - val_loss: 5.2959
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3977 - val_loss: 5.2385
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3706 - val_loss: 5.2000
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3400 - val_loss: 5.2103
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3143 - val_loss: 5.1705
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2891 - val_loss: 5.1988
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2674 - val_loss: 5.1643

In [14]:
y_pred = model.predict(X_test)
print(y_pred)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[ 7.0787477]
 [10.158277 ]
 [ 3.718502 ]
 [10.86486  ]
 [12.374291 ]
 [10.892686 ]
 [19.97069  ]
 [ 9.807595 ]
 [ 5.4363027]
 [10.849204 ]
 [14.775666 ]
 [ 5.797477 ]
 [13.219741 ]
 [10.643579 ]
 [16.174068 ]
 [ 8.684113 ]
 [ 6.719995 ]
 [12.000075 ]
 [15.453864 ]
 [ 8.315039 ]
 [13.585292 ]
 [16.742413 ]
 [15.030039 ]
 [ 8.675435 ]
 [ 8.600292 ]
 [20.010859 ]
 [10.72852  ]
 [ 9.211452 ]
 [17.144781 ]
 [11.832124 ]
 [11.020448 ]
 [ 6.983915 ]
 [15.102477 ]
 [10.171863 ]
 [ 3.9896371]
 [ 5.5182076]
 [-0.8270865]
 [16.141464 ]
 [11.298894 ]
 [ 9.489985 ]
 [ 7.100499 ]
 [ 9.787213 ]
 [12.851535 ]
 [ 4.8333554]
 [14.361921 ]
 [ 9.535697 ]
 [11.8676815]
 [15.505136 ]
 [12.059279 ]
 [18.768236 ]
 [14.676793 ]
 [16.536291 ]
 [10.896445 ]
 [ 8.373605 ]
 [ 4.083021 ]
 [13.050957 ]
 [11.2471285]
 [ 6.4480495]
 [14.766194 ]
 [17.759722 ]
 [13.068439 ]
 [ 8.932702 ]
 [ 5.521525 ]
 [ 4.608963 ]
 [-0.3357394]
 [16.339277 ]
 [ 7.330084 ]
 [10.864718 ]
 [ 9.371295 ]
 [16.26842  ]
 [ 9.407426 ]
 [ 8.841846 ]
 [13.373087 ]
 [19.848873 ]
 [ 8.28668  ]
 [ 7.271961 ]
 [11.30535  ]
 [14.27018  ]
 [ 4.0663776]]

In [15]:
print(y_pred[:5])

[[ 7.0787477]
 [10.158277 ]
 [ 3.718502 ]
 [10.86486  ]
 [12.374291 ]]

In [16]:
r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

R² Score: 0.6477084159851074